
var FONT_LIST = [
    {"name": "Arial",                 "value": "Arial"                },
    {"name": "Agency FB Bold",        "value": "Agency FB Bold"       },
    {"name": "Buxton Sketch",         "value": "Buxton Sketch"        },
    {"name": "Bell MT Bold",          "value": "Bell MT Bold"         },
    {"name": "Bodoni MT Bold Italic", "value": "Bodoni MT Bold Italic"},
    {"name": "Bookman Old Style",     "value": "Bookman Old Style"    },
    {"name": "Cambria",               "value": "Cambria"              },
    {"name": "Calibri",               "value": "Calibri"              },
    {"name": "Calibri Light",         "value": "Calibri Light"        },
    {"name": "Calibri Italic",        "value": "Calibri Italic"       },
    {"name": "Calisto MT",            "value": "Calisto MT"           },
    {"name": "Cambria",               "value": "Cambria"              },
    {"name": "Cambria Bold",          "value": "Cambria Bold"         },
    {"name": "Cambria Italic",        "value": "Cambria Italic"       },
    {"name": "Consolas",              "value": "Consolas"             },
    {"name": "Century Gothic",        "value": "Century Gothic"       },
    {"name": "DengXian",              "value": "DengXian"             },
    {"name": "Ebrima",                "value": "Ebrima"               },
    {"name": "Euphemia",              "value": "Euphemia"             },
    {"name": "Felix Titling",         "value": "Felix Titling"        },
    {"name": "FixedSys",              "value": "FixedSys"             },
    {"name": "Franklin Gothic",       "value": "Franklin Gothic"      },
    {"name": "Georgia",               "value": "Georgia"              },
    {"name": "Gisha",                 "value": "Gisha"                },
    {"name": "Gulim",                 "value": "Gulim"                },
    {"name": "High Tower Text",       "value": "High Tower Text"      },
    {"name": "Impact",                "value": "Impact"               },
    {"name": "Iskoola Pota",          "value": "Iskoola Pota"         },
    {"name": "KaiTi",                 "value": "KaiTi"                },
    {"name": "Khmer UI",              "value": "Khmer UI"             },
    {"name": "Levenim MT",            "value": "Levenim MT"           },
    {"name": "meiryo",                "value": "meiryo"               },
    {"name": "Meiryo UI",             "value": "Meiryo UI"            },
    {"name": "MS UI Gothic",          "value": "MS UI Gothic"         },
    {"name": "Microsoft MHei",        "value": "Microsoft MHei"       },
    {"name": "Microsoft NeoGothic",   "value": "Microsoft NeoGothic"  },
    {"name": "Microsoft Tai Le",      "value": "Microsoft Tai Le"     },
    {"name": "Mistral",               "value": "Mistral"              },
    {"name": "Modern",                "value": "Modern"               },
    {"name": "Modern No. 20",         "value": "Modern No. 20"        },
    {"name": "Nyala",                 "value": "Nyala"                },
    {"name": "OCR A Extended",        "value": "OCR A Extended"       },
    {"name": "PMingLiU",              "value": "PMingLiU"             },
    {"name": "Palatino Linotype",     "value": "Palatino Linotype"    },
    {"name": "Roman",                 "value": "Roman"                },
    {"name": "Script",                "value": "Script"               },
    {"name": "Segoe Maker",           "value": "Segoe Maker"          },
    {"name": "Segoe WP",              "value": "Segoe WP"             },
    {"name": "Segoe WP SemiLight",    "value": "Segoe WP SemiLight"   },
    {"name": "Shruti",                "value": "Shruti"               },
    {"name": "SimHei",                "value": "SimHei"               },
    {"name": "Small Fonts",           "value": "Small Fonts"          },
    {"name": "Stencil",               "value": "Stencil"              },
    {"name": "Terminal",              "value": "Terminal"             },
    {"name": "Vani",                  "value": "Vani"                 },
    {"name": "Verdana",               "value": "Verdana"              },
    {"name": "Wingding",              "value": "Wingding"             },
];

FONT_LIST = FONT_LIST.filter((x, i, self) => self.indexOf(x) === i);

var CHAR_LIST = [
    {"value": "0" , "name":"a"},
    {"value": "1" , "name":"b"},
    {"value": "2" , "name":"c"},
    {"value": "3" , "name":"d"},
    {"value": "4" , "name":"e"},
    {"value": "5" , "name":"f"},
    {"value": "6" , "name":"g"},
    {"value": "7" , "name":"h"},
    {"value": "8" , "name":"i"},
    {"value": "9" , "name":"j"},
    {"value": "10", "name":"k"},
    {"value": "11", "name":"l"},
    {"value": "12", "name":"m"},
    {"value": "13", "name":"n"},
    {"value": "14", "name":"o"},
    {"value": "15", "name":"p"},
    {"value": "16", "name":"q"},
    {"value": "17", "name":"r"},
    {"value": "18", "name":"s"},
    {"value": "19", "name":"t"},
    {"value": "20", "name":"u"},
    {"value": "21", "name":"v"},
    {"value": "22", "name":"w"},
    {"value": "23", "name":"x"},
    {"value": "24", "name":"y"},
    {"value": "25", "name":"z"},
    {"value": "26", "name":"A"},
    {"value": "27", "name":"B"},
    {"value": "28", "name":"C"},
    {"value": "29", "name":"D"},
    {"value": "30", "name":"E"},
    {"value": "31", "name":"F"},
    {"value": "32", "name":"G"},
    {"value": "33", "name":"H"},
    {"value": "34", "name":"I"},
    {"value": "35", "name":"J"},
    {"value": "36", "name":"K"},
    {"value": "37", "name":"L"},
    {"value": "38", "name":"M"},
    {"value": "39", "name":"N"},
    {"value": "40", "name":"O"},
    {"value": "41", "name":"P"},
    {"value": "42", "name":"Q"},
    {"value": "43", "name":"R"},
    {"value": "44", "name":"S"},
    {"value": "45", "name":"T"},
    {"value": "46", "name":"U"},
    {"value": "47", "name":"V"},
    {"value": "48", "name":"W"},
    {"value": "49", "name":"X"},
    {"value": "50", "name":"Y"},
    {"value": "51", "name":"Z"},
    {"value": "52", "name":"0"},
    {"value": "53", "name":"1"},
    {"value": "54", "name":"2"},
    {"value": "55", "name":"3"},
    {"value": "56", "name":"4"},
    {"value": "57", "name":"5"},
    {"value": "58", "name":"6"},
    {"value": "59", "name":"7"},
    {"value": "60", "name":"8"},
    {"value": "61", "name":"9"},
    {"value": "62", "name":"."},
    {"value": "63", "name":","},
    {"value": "64", "name":"_"},
    {"value": "65", "name":"-"},
    {"value": "66", "name":"@"},
    {"value": "67", "name":"<"},
    {"value": "68", "name":">"},
    {"value": "69", "name":"?"},
    {"value": "70", "name":"!"}   
];

var ROTATE_LIST = [
    {"name": -20, "value":-Math.PI * 20/180},
    {"name": -15, "value":-Math.PI * 15/180},
    {"name": -10, "value":-Math.PI * 10/180},
    {"name": -5,  "value":-Math.PI * 5/180 },
    {"name": 0,   "value":0                },
    {"name": 5,   "value":Math.PI * 5/180  },
    {"name": 10,  "value":Math.PI * 10/180 },
    {"name": 15,  "value":Math.PI * 15/180 },
    {"name": 20,  "value":Math.PI * 20/180 }
];